export const AUTH_SIGNUP_PENDING = 'AUTH_SIGNUP_PENDING';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';

export const AUTH_GET_ACCESS_TOKEN_PENDING = 'AUTH_GET_ACCESS_TOKEN_PENDING';
export const AUTH_GET_ACCESS_TOKEN_SUCCESS = 'AUTH_GET_ACCESS_TOKEN_SUCCESS';
export const AUTH_GET_ACCESS_TOKEN_FAILURE = 'AUTH_GET_ACCESS_TOKEN_FAILURE';

export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_GET_CURRENT_USER_PENDING = 'AUTH_GET_CURRENT_USER_PENDING';
export const AUTH_GET_CURRENT_USER_SUCCESS = 'AUTH_GET_CURRENT_USER_SUCCESS';
export const AUTH_GET_CURRENT_USER_FAILURE = 'AUTH_GET_CURRENT_USER_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
