export const AUTH_SIGNUP_PENDING = 'AUTH_SIGNUP_PENDING';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';

export const AUTH_GET_ACCESS_TOKEN_PENDING = 'AUTH_GET_ACCESS_TOKEN_PENDING';
export const AUTH_GET_ACCESS_TOKEN_SUCCESS = 'AUTH_GET_ACCESS_TOKEN_SUCCESS';
export const AUTH_GET_ACCESS_TOKEN_FAILURE = 'AUTH_GET_ACCESS_TOKEN_FAILURE';
