export const BOOKS_GET_ALL_PENDING = 'BOOKS_GET_ALL_PENDING';
export const BOOKS_GET_ALL_SUCCESS = 'BOOKS_GET_ALL_SUCCESS';
export const BOOKS_GET_ALL_FAILURE = 'BOOKS_GET_ALL_FAILURE';

export const BOOKS_GET_ONE_PENDING = 'BOOKS_GET_ONE_PENDING';
export const BOOKS_GET_ONE_SUCCESS = 'BOOKS_GET_ONE_SUCCESS';
export const BOOKS_GET_ONE_FAILURE = 'BOOKS_GET_ONE_FAILURE';
