export const USERS_GET_ALL_PENDING = 'USERS_GET_ALL_PENDING';
export const USERS_GET_ALL_SUCCESS = 'USERS_GET_ALL_SUCCESS';
export const USERS_GET_ALL_FAILURE = 'USERS_GET_ALL_FAILURE';

export const USERS_GET_ONE_PENDING = 'USERS_GET_ONE_PENDING';
export const USERS_GET_ONE_SUCCESS = 'USERS_GET_ONE_SUCCESS';
export const USERS_GET_ONE_FAILURE = 'USERS_GET_ONE_FAILURE';
